### ISSUE TITLE
Create C struct representation of GDF and create/import/destroy functions

### ISSUE THREAD

**Issue by seibert** [gpuopenanalytics/libgdf#2]
This will be a simple host-side C struct with device pointers and metadata to make it easy to write CUDA code operating on columns of the structure.

**Comment by sklam** [comment]
Does these satisfy this issue?

* https://github.com/gpuopenanalytics/libgdf/blob/c7bbfd4058f997a5c1eb933e3ae357f343202725/include/gdf/cffi/types.h#L21-L26
* https://github.com/gpuopenanalytics/libgdf/blob/c7bbfd4058f997a5c1eb933e3ae357f343202725/src/column.cpp

**Comment by sklam** [comment]
#10 have provided a basic implementation for this.  Closing
