### ISSUE TITLE
CMake files assume that all thirdparty libraries are installed in $CONDA_PREFIX

### ISSUE THREAD

**Issue by wesm** [gpuopenanalytics/libgdf#37]
Per https://groups.google.com/d/msg/gpuopenanalytics/80wqDq0Ap4g/Np1nK8tzAQAJ I would like to see efforts merge around build systems / IPC / reusable analytics kernels for Arrow memory, but in the meantime -- this library can only be built if the required thirdparty libraries (Flatbuffers, Arrow) are installed in a root directory at `$CONDA_PREFIX`.

**Comment by aucahuasi** [comment]
Done!

**Comment by kkraus14** [comment]
@aucahuasi Could you link to the pull request or changes where these fixes are?

**Comment by aucahuasi** [comment]
Hi @kkraus14 we will try to make the pull request tomorrow.
For now I just need @williamBlazing or @felipeblazing can check the code.

**Comment by kkraus14** [comment]
This is resolved by #56. Closing.
