### ISSUE TITLE
hashjoin invalid global write 

### ISSUE THREAD

**Issue by sklam** [gpuopenanalytics/libgdf#57]
I am seeing a invalid `__global__` write in `probe_hash_tbl`.  The error is initially silent (only seen thru cuda-memcheck) but, when accumulated, it seems to cause corruption of the host heap (i.e. `free()` reporting error and segfaults).

I have implemented [a reproducer](https://github.com/sklam/libgdf/commit/09f86e3113ac15c53e49238576872cbfeea25149#diff-0357c877510126d5f74d5ed0ae052053R346) in branch https://github.com/sklam/libgdf/tree/bug/probe_hash_tbl, which is based on the current master.  

The reproducer test can be triggered with `cuda-memcheck py.test tests/test_joining.py::test_multi_merge_left` after `make && make copy_python`.  

ping @nsakharnykh

**Comment by sklam** [comment]
Here's the log from cuda-memcheck: https://gist.github.com/sklam/179c03a11dd33d128db8fab7eeafc5b6

**Comment by nsakharnykh** [comment]
I can reproduce it on my end
