### ISSUE TITLE
Shouldn't need "-DHashJoin" as a cmake option 

### ISSUE THREAD

**Issue by kkraus14** [gpuopenanalytics/libgdf#74]
https://github.com/gpuopenanalytics/libgdf/blob/master/CMakeLists.txt#L94

Hash joins should always be enabled by default, and sort/hash based joins should both be exposed.

**Comment by mike-wendt** [comment]
Good to know I'll make a note and make adjustments for gpuCI build scripts, which also will be in a repo next week

**Comment by kkraus14** [comment]
@mike-wendt just for clarification: this issue is that we shouldn't need a build flag, and we should have a way to expose both sort and hash based joins so that future schedulers or power users can leverage either or both.

**Comment by mike-wendt** [comment]
Gotcha after seeing another build process i saw it being explicitly called and added it in. I didn’t dive into the cMake to see it was on by default.
