### ISSUE TITLE
test_hashing fails randomly 

### ISSUE THREAD

**Issue by jrhemstad** [gpuopenanalytics/libgdf#77]
The test_hasing pytest seems to fail randomly. It can be run in isolation and works, but fails when run as part of the complete test suite.

```
15:16:47 =================================== FAILURES ===================================
15:16:47 _________________________________ test_hashing _________________________________
15:16:47 
15:16:47     def test_hashing():
15:16:47         # Make data
15:16:47         nrows = 8
15:16:47         dtypes = [np.int8, np.int16, np.int32, np.int64, np.float32]#, np.float64] # dtypes as number of columns
15:16:47     
15:16:47         # pytest for hashing fails if called collectively on folder and if number of columns>5, but works well if called seperately like
15:16:47         # pytest --cache-clear -vvs ~/libgdf/python/tests/test_hashing.py
15:16:47     
15:16:47         hash_input = []
15:16:47         for dt in dtypes:
15:16:47             hi = np.array(np.random.randint(0, 28, nrows), dtype=dt)
15:16:47             hi[-1] = hi[0]
15:16:47             hash_input.append(hi)
15:16:47     
15:16:47         ncols = len(hash_input)
15:16:47         magic = libgdf.GDF_HASH_MURMUR3
15:16:47     
15:16:47         with _make_hash_input(hash_input, ncols) as col_input:
15:16:47             # Hash
15:16:47             hashed_column = _call_hash_multi(libgdf.gdf_hash, ncols, col_input, magic, nrows)
15:16:47     
15:16:47         # Check if first and last row are equal
15:16:47 >       assert tuple([hashed_column[0]]) == tuple([hashed_column[-1]])
15:16:47 E       assert (-479244108,) == (-1102096448,)
15:16:47 E         At index 0 diff: -479244108 != -1102096448
15:16:47 E         Full diff:
15:16:47 E         - (-479244108,)
15:16:47 E         + (-1102096448,)
15:16:47 
15:16:47 test_hashing.py:95: AssertionError
```

**Comment by kkraus14** [comment]
I did some digging and the issue is stemming from float32 columns only and all of the hashing is wrong for it, but only when run as part of the collection and not individually. I added a print statement to print the input and dtype and then the hashed result and here's the result:
```
[ 0. 16.  4. 15. 23. 15.  0.  0.] float32
[ -479244108 -2078410840   502904503  1049972374   767157442 -1627207307
   189202023 -1102096448]
```

**Comment by kkraus14** [comment]
@yashv28 I'm hitting it with only 3 dtypes (int8, int16, float32) currently. I think we should address the issue instead of working the tests around it.

**Comment by mt-jones** [comment]
What’s the status on this issue?

**Comment by kkraus14** [comment]
@mt-jones it still fails consistently with weird behavior. If the file is renamed to run in a different order than it currently runs, it succeeds. Additionally, if the test is run standalone it succeeds.

**Comment by mt-jones** [comment]
@kkraus14 this sounds like a caching issue. Is there a way to confirm this?

**Comment by yashv28** [comment]
So I did some digging around to see if the values passed into `libgdf` are proper and I found out that if I call `pytest` collectively then this happened:
```
Column <class 'numpy.int8'> -> [14  0  0  0  0  0  0  0]
Column <class 'numpy.int16'> -> [    0     0     0 16768     0 16512     0 16752]
Column <class 'numpy.int32'> -> [ 3 22 17 17 14  5 24  3]
Column <class 'numpy.int64'> -> [14 10 24 21 26 24  8 14]
Column <class 'numpy.float32'> -> [ 0. 16.  4. 15. 23. 15.  0.  0.]
Column <class 'numpy.float64'> -> [ 7. 15. 19. 19.  9. 15.  7.  7.]
```

and when calling `pytest test_hashing.py` then the inputs were correct as expected:
```
Column <class 'numpy.int8'> -> [21 17  0  8 16 27 10 21]
Column <class 'numpy.int16'> -> [22 12 11 26 17 21 14 22]
Column <class 'numpy.int32'> -> [12 14 21 20 23 26 11 12]
Column <class 'numpy.int64'> -> [15  3 20 12  7 26  1 15]
Column <class 'numpy.float32'> -> [25. 26. 15. 14. 22.  8.  6. 25.]
Column <class 'numpy.float64'> -> [ 2. 12. 15. 23. 19. 19.  0.  2.]
```
I even changed the order of columns and found that first 2 columns weren't being passed with their original values.

**Comment by mike-wendt** [comment]
Anyone actively working on this?

**Comment by kaatish** [comment]
I am trying to replicate this on my machine but have been unable to do so till now.

**Comment by yashv28** [comment]
I may have a [**potential fix**](https://github.com/yashv28/libgdf). Can anybody confirm?

**Comment by nsakharnykh** [comment]
Do we understand why this is fixing the issue?

**Comment by yashv28** [comment]
So the output from the _make_hash_input, specially for the first 2 columns(irrespective of dtypes) gets scrambled, so this fix introduces some dummy columns, and ignores them just before calling gdf_hash.

@kaatish has a better solution, he introduced a loop with lists for new_column() and device inputs, which works w/o using any dummy data.
