### ISSUE TITLE
Travis CI should use xenial as the base distro

### ISSUE THREAD

**Issue by mike-wendt** [gpuopenanalytics/libgdf#80]
Right now we are using `trusty` but support for CUDA 9.2 and others are being actively tested on `xenial`

In addition all gpuCI tests run on `xenial` as the base so this will help with compatibility there

**Comment by kkraus14** [comment]
It seems like Travis CI doesn't support xenial and don't have any ETA on support for xenial or bionic.

https://docs.travis-ci.com/user/reference/overview/
