### ISSUE TITLE
Drop Python 2.7 support 

### ISSUE THREAD

**Issue by kkraus14** [gpuopenanalytics/libgdf#81]
Seeing as numerous other major projects (some of which we depend on) have plans for dropping Python 2.7 support, we should drop Python 2.7 support now while we're still under heavy development and haven't started doing formal releases yet.

If I receive positive feedback (or no feedback) to this issue I'll follow up with a WIP pull request removing the Python 2.7 builds from CI.

**Comment by kkraus14** [comment]
PyGDF Issue: https://github.com/gpuopenanalytics/pygdf/issues/174

**Comment by datametrician** [comment]
Most Python 2.7 EOL is 2019... I see no point adding it to deprecate in less than a year.
