### ISSUE TITLE
Move remaining tests from libgdf/tests to libgdf/src/tests

### ISSUE THREAD

**Issue by harrism** [gpuopenanalytics/libgdf#96]
Most tests were moved to libgdf/src/tests in https://gitlab-master.nvidia.com/RAPIDS/libgdf/commit/1850b5f1238cc1d1e09d2fac7d03c15ca64badfd but there are still a few in libgdf/tests that need to be moved.

**Comment by nsakharnykh** [comment]
@yashv28 can you look into this one?

**Comment by yashv28** [comment]
[Done](https://github.com/gpuopenanalytics/libgdf/pull/97)
